name: Validate & Release

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # HACS validation (set the correct category)
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "integration"

      # hassfest (Home Assistant validator)
      - name: Hassfest
        uses: home-assistant/actions/hassfest@main

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Compare tag (v1.3.0) with manifest.json "version": "1.3.0"
      - name: Ensure manifest version matches tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG_NO_V="${TAG#v}"
          MANIFEST_VERSION=$(jq -r '.version' custom_components/<your_domain>/manifest.json)
          echo "Tag: $TAG, Manifest: $MANIFEST_VERSION"
          test "$MANIFEST_VERSION" = "$TAG_NO_V"

      # Create a GitHub Release (use your preferred action if you like)
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
