name: Validate & Release (HACS + hassfest)

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: write  # needed for creating releases

jobs:
  validate:
    name: Validate (HACS + hassfest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # HACS validator (repo-level + custom_components structure checks)
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands

      # Home Assistant validator (manifest/schema/structure/translations)
      - name: Run hassfest (exclude brands)
        run: |
            docker run --rm -v "${{ github.workspace }}:/workspace" ghcr.io/home-assistant/hassfest:latest --action validate --exclude-brands

  release:
    name: Release on tag
    if: startsWith(github.ref, 'refs/tags/')
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure manifest.json version matches tag vX.Y.Z
      - name: Ensure manifest version matches tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG_NO_V="${TAG#v}"
          MANIFEST_VERSION=$(jq -r '.version' custom_components/<your_domain>/manifest.json)
          echo "Tag: $TAG | Manifest: $MANIFEST_VERSION"
          test "$MANIFEST_VERSION" = "$TAG_NO_V"

      # Publish a GitHub Release for HACS users
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
